### ISSUE TITLE
System.IndexOutOfRangeException when posting comment from blog

### ISSUE THREAD

**Issue by Teknikaali** [Teknikaali/jekyll-blog-comments#13]
After fixing post_id -> postId from the blog this happens when posting a comment from https://kettunen.dev/test/2019/09/21/test-post-01.html
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ApplicationCore.PullRequestService.TryCreatePullRequestAsync(Comment comment)
   at ApplicationCore.PostCommentService.PostCommentAsync(IFormCollection form) in D:\a\jekyll-blog-comments\jekyll-blog-comments\ApplicationCore\Services\PostComment\PostCommentService.cs:line 50
   at JekyllBlogCommentsAzure.PostCommentToPullRequestFunction.Run(HttpRequest request, ILogger logger) in D:\a\jekyll-blog-comments\jekyll-blog-comments\JekyllBlogCommentsAzure\PostCommentToPullRequestFunction.cs:line 43
```

Here is a more detailed exception from Azure Live Metrics:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: PostComment
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ApplicationCore.PullRequestService.TryCreatePullRequestAsync(Comment comment)
   at ApplicationCore.PostCommentService.PostCommentAsync(IFormCollection form) in D:\a\jekyll-blog-comments\jekyll-blog-comments\ApplicationCore\Services\PostComment\PostCommentService.cs:line 50
   at JekyllBlogCommentsAzure.PostCommentToPullRequestFunction.Run(HttpRequest request, ILogger logger) in D:\a\jekyll-blog-comments\jekyll-blog-comments\JekyllBlogCommentsAzure\PostCommentToPullRequestFunction.cs:line 43
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 322
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
```

**Comment by Teknikaali** [comment]
It's a bit unclear from the exception where exactly the index was outside the bounds.
Let's improve the exception handling so problems like this are easier to fix in future.

**Comment by Teknikaali** [comment]
After ed52526 commit this is now the error message:
```
Found 3 configuration error(s) in WebConfiguration:
The GitHubToken field is required.,
The PullRequestRepository field is required.,
The Website field is required.
```

**Comment by Teknikaali** [comment]
There was some confusion about how to use the Azure Function's configuration.
It was all about using environment variables.
